app = "crystal-ai-voice-new-app" # Your app name, ensure it's unique
primary_region = "sin" # Your preferred region

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
  celery = "celery -A tasks.worker.celery_app worker --loglevel=info"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["web"]

# Define VM configuration for the 'web' process group
[[vm]]
  processes = ["web"] # This VM config applies ONLY to 'web' machines
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[[mounts]] # This mount applies ONLY to 'web' machines
  processes = ["web"] # Link this mount to the 'web' process
  source="voiceai_new_app_audio"
  destination="/tmp_shared_audio"
  auto_destroy = true # ADD THIS LINE: Allow the volume to be destroyed and recreated with the machine

# Define VM configuration for the 'celery' process group
[[vm]]
  processes = ["celery"] # This VM config applies ONLY to 'celery' machines
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb" # Celery might need less memory, adjust if desired (e.g., 256mb)

[[mounts]] # This mount applies ONLY to 'celery' machines
  processes = ["celery"] # Link this mount to the 'celery' process
  source="voiceai_new_app_logs"
  destination="/app/logs"
  auto_destroy = true # ADD THIS LINE: Allow the volume to be destroyed and recreated with the machine
